// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvprtwbmvsmkyjayoakz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cHJ0d2JtdnNta3lqYXlvYWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTU0NDIsImV4cCI6MjA2Mzk5MTQ0Mn0.n-qGzogRNaU3EARxqPVz0wVuWCtcKA3gcxES_L0UV8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);